// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("DependentTypes")>]
[<assembly: AssemblyProductAttribute("DependentTypes")>]
[<assembly: AssemblyDescriptionAttribute("F# DependentTypes")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "DependentTypes"
    let [<Literal>] AssemblyProduct = "DependentTypes"
    let [<Literal>] AssemblyDescription = "F# DependentTypes"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
