// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("DependentTypesConsole")>]
[<assembly: AssemblyProductAttribute("DependentTypes")>]
[<assembly: AssemblyDescriptionAttribute("F# DependentTypes")>]
[<assembly: AssemblyVersionAttribute("0.0.3")>]
[<assembly: AssemblyFileVersionAttribute("0.0.3")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "DependentTypesConsole"
    let [<Literal>] AssemblyProduct = "DependentTypes"
    let [<Literal>] AssemblyDescription = "F# DependentTypes"
    let [<Literal>] AssemblyVersion = "0.0.3"
    let [<Literal>] AssemblyFileVersion = "0.0.3"
    let [<Literal>] AssemblyConfiguration = "Release"
